### ISSUE TITLE
Display banners and make them configurable

### ISSUE THREAD

**Issue by tegioz** [cncf/landscape2#107]

**Comment by cjyabraham** [comment]
Is there an ETA on this issue? The CNCF marketing team are wanting to get a Kubecon EU banner up on landscape.

**Comment by tegioz** [comment]
Yes, we are aiming at Monday. Actually we prepared a mockup yesterday 🙂

<img width="1360" alt="kubecon-banner-1" src="https://github.com/cncf/landscape2/assets/1213902/07c493d0-46cb-42bf-9d14-3b370bc4d1dc">

<img width="1360" alt="kubecon-banner-2" src="https://github.com/cncf/landscape2/assets/1213902/b0937215-d3c3-41dd-8a46-92acec1058b7">

**Comment by cjyabraham** [comment]
Could you feature just the following banner?

![kceu24_promo_2400x300](https://github.com/cncf/landscape2/assets/463160/7e927814-29c7-4d03-a762-72cf6d74bcda)

Please link it to 
`https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/register/?utm_source=landscape&utm_medium=all&utm_campaign=kubeconeu24&utm_content=slim-banner`

You don't need to show Kubecon NA yet as it is a long way off.

**Comment by tegioz** [comment]
@cjyabraham do you have a stable url for that banner that we can use on the CNCF landscape? i.e. if you've pushed it to a GH repo, like the artwork one, we can use the raw url. This will be configurable from the landscape settings file, similarly to the GTM setup.

**Comment by cjyabraham** [comment]
You can use this one:
`https://www.cncf.io/wp-content/uploads/2024/01/kceu24_promo_2400x300.png`
