### ISSUE TITLE
Searchbar not working 

### ISSUE THREAD

**Issue by kumarankit999** [cncf/landscape2#170]
If we write any keyword in the searchbar, the keyword get self-deleted and we are not able to find the information regarding my keyword

![image](https://github.com/cncf/landscape2/assets/111564362/539407d1-a3b5-4327-b1d0-74c29be18ca5)

**Comment by tegioz** [comment]
Hi @kumarankit999 👋

Thanks for reporting this! Could you please share some details about the OS/browser where you experiencing this issue?

It should look something like this:

<img width="675" alt="search" src="https://github.com/cncf/landscape2/assets/1213902/cf4e892b-d0b2-49dc-bad1-6c08fcca385b">

**Comment by tegioz** [comment]
At the moment if no results are found, we are not displaying anything yet to let the user know (we'll take care of this soon). Is it possible that it was just that? Could you try searching for some term that will produce results (like `helm`)?

**Comment by kumarankit999** [comment]
Hey @tegioz, I am seeing this error by using chrome on windows.
Involve me if needed, I would love to help
