### ISSUE TITLE
Bug: flickering Header Navbar on Mid and Small Screens During Scroll

### ISSUE THREAD

**Issue by seokho-son** [cncf/landscape2#331]
The new Landscape2 looks great! Thanks all!

I just noticed a bug in the Landscape2 (https://cncf.landscape2.io/). Hope following report is useful to the team.

The content within the red box is experiencing flickering when the page is scrolled slightly. This issue persists across both Chrome and a mobile browser and is noticeable on mid to small screen sizes. It seems there may be a conflict or a bug within the layout's resources, potentially within the responsive design implementation.

![image](https://github.com/cncf/landscape2/assets/5966944/1c9281c1-f54b-4f52-8c03-104d977b1aa6)

I guess there are some conflicts among resources in the layout.

![image](https://github.com/cncf/landscape2/assets/5966944/a2ec6c09-2a1a-4eb1-8403-14f0037dc338)

**Comment by tegioz** [comment]
Thanks @seokho-son for reporting this! @cynthia-sg has just pushed a fix and we'll deploy it shortly 🙂
