### ISSUE TITLE
Change pink shade to "CNCF pink"

### ISSUE THREAD

**Issue by cjyabraham** [cncf/landscape2#338]
Is it possible to change the pink shade to [the one we use for CNCF](https://www.cncf.io/brand-guidelines/#colors), which is #D62293. Also, the current white-on-pink colors don't meet WCAG 2.1 AA accessibility guidelines.
![Screenshot 2023-11-08 at 8 49 48 PM](https://github.com/cncf/landscape2/assets/463160/f8515c64-de0a-427a-bb11-a130199a2880)

**Comment by tegioz** [comment]
Thanks @cjyabraham, done in cncf/landscape2-sites#56.

We still have some more work to do related to accessibility though (#104).
