### ISSUE TITLE
Projects/organizations that should map to multiple sub-categories?

### ISSUE THREAD

**Issue by austinlparker** [cncf/landscape2#344]
Hi! Love the new landscape. One question I have as an [OpenTelemetry](https://opentelemetry.io) maintainer is how our project should fit into the greater Observability category. We support metrics, tracing, and logging but are currently pigeonholed as a tracing project. Realistically, we should be in each of the monitoring, logging, and tracing categories (although I would perhaps categorize 'monitoring' as 'metrics'...)

There's also an associated issue here, which is for organizations that map to multiple categories. Datadog, for instance, would fall under monitoring/logging/tracing as well, etc. 

While I'm not really advocating for a change in the taxonomy, it seems like there might be better categorization for this section in general? Perhaps 'Instrumentation/Telemetry', 'Storage', 'Analysis', etc.

**Comment by tegioz** [comment]
Hi again!

We've added support for the `second_path` item field to landscape2. This field allows assigning multiple categories/subcategories to an item in landscape1. Please note that [in the CNCF landscape this field is meant to be used only if the additional categories listed are in a different sub landscape](https://github.com/cncf/landscape/pull/2542#issuecomment-1274292627) (aka group in landscape2), like in the case of [wasmCloud](https://github.com/cncf/landscape/blob/68accf04db8ca5caaedc5fb68377ec5cc6572ec3/landscape.yml#L3670-L3672). In case of doubt, it's best to discuss it in the [cncf/landscape](https://github.com/cncf/landscape) repo 🙂

Will close this issue for now, please feel free to reopen if needed.

/cc @caniszczyk
