### ISSUE TITLE
Provide package manager information

### ISSUE THREAD

**Issue by jmertic** [cncf/landscape2#385]
Many of the projects in our landscapes are available in package managers such as NPM, PyPI, CRAN, etc. - could we display in the card if it has a link to the package landing page?

**Comment by tegioz** [comment]
We've added a package manager link to the item details view (when available) 🙂

You can provide it by using the `package_manager_url` field inside the item's `extra` object:

```yaml
extra:
  package_manager_url: https://...
```

<img width="356" alt="package-manager" src="https://github.com/cncf/landscape2/assets/1213902/5bd9d383-d309-41ce-a0fa-b6fd4a59432a">

Closed by #609
