### ISSUE TITLE
Display all repositories for a given project

### ISSUE THREAD

**Issue by jmertic** [cncf/landscape2#386]
It looks like the ability to show all the repositories for a given project went away. That would be great to have back :-)

In addition - I like the stats view; could we have the ability for rolled up stats for all repos, and then also be able to select a single repo for stats?

**Comment by jmertic** [comment]
Thanks! Data issue on my end for the one that didn't show up, but like this UX going forward!

**Comment by skushagra9** [comment]
Hi , I am here for gsoc , please tell what all issues should I contribute to

**Comment by tegioz** [comment]
This is ready @jmertic 🙂

<img width="1153" alt="repositories-selector" src="https://github.com/cncf/landscape2/assets/1213902/7e639f7a-b1b3-4b3a-9a32-66ecccabe123">
