### ISSUE TITLE
Link to 'good first issues'

### ISSUE THREAD

**Issue by jmertic** [cncf/landscape2#387]
We encourage projects to use the 'good first issues' tag for identifying issues that are good for newcomers, could we incorporate that into the card somehow? Maybe even with a counter of the number of good first issues?

**Comment by tegioz** [comment]
Hi again!

Are you familiar with [CLOTributor](https://clotributor.dev)? One option would be to add a link to CLOTributor filtering by the corresponding foundation and project.

<img width="1426" alt="clotributor" src="https://github.com/cncf/landscape2/assets/1213902/c3f99390-9261-4ef4-bce6-46906c3f1e69">

There is also [CLOMonitor](https://clomonitor.io), which we've already partially integrated in landscape2 by displaying a summary report in the item details view (when available).

<img width="1153" alt="clomonitor" src="https://github.com/cncf/landscape2/assets/1213902/280b9332-2515-40ec-94be-3d45a1bd51bc">

It's easy to add more foundations to both sites, so if you are interested we could discuss it 🙂 Fore more details about how CLOTributor works, please take a look at the [README file in the source repository](https://github.com/cncf/clotributor#clotributor).

**Comment by jmertic** [comment]
I'm somewhat familar with that tool. It does seem interesting, buPt I'm unsure of the overall alignment with the recommended best practices and project measurement tooling for LF projects. Probably a much larger discussion ;-)

For this, could we just simply use the existing 'good first issues' badge, but better integrate it into the UI? https://github.com/badges/shields#contributing

**Comment by jmertic** [comment]
Thanks! If we could also have the data for good first issues that we could pull out in a CSV/API, that would be great.

Is CLOTributor connected to landscape-listed projects? I like the idea and would love to make it something that could be used for my foundations.

**Comment by tegioz** [comment]
> If we could also have the data for good first issues that we could pull out in a CSV/API, that would be great.

You could use the same -undocumented yet 😇- API that powers the UI if you'd like 🙂 (output is json though).

Sample request to get good first issues for CNCF projects:

<https://clotributor.dev/api/issues/search?limit=20&offset=0&good_first_issue=true&foundation[0]=cncf>

> Is CLOTributor connected to landscape-listed projects? I like the idea and would love to make it something that could be used for my foundations.

Not yet, but the plan is to eventually have it feed from the landscape data, yes. At the moment both CLOMonitor and CLOTributor feed from the same [data files hosted on the CLOMonitor repo](https://github.com/cncf/clomonitor/tree/main/data).

**Comment by tegioz** [comment]
Done!

Closed by #582 

<img width="1153" alt="good-first-issues" src="https://github.com/cncf/landscape2/assets/1213902/3223e8c0-4109-4d42-8998-1fcdc2b41435">
