### ISSUE TITLE
Add resizer js for iframe embeds

### ISSUE THREAD

**Issue by cjyabraham** [cncf/landscape2#413]
Note that [the current landscape embed](https://www.cncf.io/about/members/) uses [an iframeResizer js script](https://landscape.cncf.io/iframeResizer.js?ver=1703094089) to resize the iframe to show all content once it's loaded so that no scrolling is required inside the iframe itself. It makes it seem like the content is actually part of the page. Is it possible to have that same functionality for the new landscape embeds?

**Comment by tegioz** [comment]
Closed by #424

This feature can be enabled by adding `iframe-resizer=true` to the embed url ([demo](https://codepen.io/cynthiasg/pen/WNmQjje)).
