### ISSUE TITLE
Poorly sized logos

### ISSUE THREAD

**Issue by cjyabraham** [cncf/landscape2#430]
I'm not sure how the logos are processed or where they come from but the [MacStadium](https://l2.cncf.io/?group=projects-and-products) logo is very small on landscape2. On [the old landscape](https://landscape.cncf.io/card-mode?selected=mac-stadium-member) it looks fine. [Emagine IT](https://l2.cncf.io/?group=projects-and-products) has the same problem.
![Screenshot 2024-01-08 at 2 25 15 PM](https://github.com/cncf/landscape2/assets/463160/a8b8d528-6629-44eb-be27-13518992a9d7)

**Comment by tegioz** [comment]
Thanks @cjyabraham, this has been fixed in #444.
