### ISSUE TITLE
Landscape v2 is listing OpenTelemetry incorrectly; Popup card view is also inaccurate for OpenTelemetry

### ISSUE THREAD

**Issue by alolita** [cncf/landscape2#442]
OpenTelemetry is incorrectly listed in the tracing category of the Observability & Analysis section in the new v2 of the Landscape graph chart. See attached screenshot. OpenTelemetry supports metrics, tracing and logging and the current categorization is wrong.

The project is also being represented inaccurately in the popup card (see attached screenshot) by listing the OpenTelemetry Java SDK. OpenTelemetry has tens of other components beyond the Java SDK and should be represented in full.

Please correct the graph asap. Let me know if you need more clarity.

<img width="1107" alt="landscape2-otel-inaccurate-listing" src="https://github.com/cncf/landscape2/assets/1942529/dd248d74-66ab-482b-a980-90a37ceaf21f">

**Comment by tegioz** [comment]
Hi @alolita 👋

Landscape2 feeds from the same [landscape.yml](https://github.com/cncf/landscape/blob/0b71c07e0950fe915e192d370b7fb54c5560e618/landscape.yml#L10067-L10094) file as landscape1. If you visit the current landscape you'll notice that OpenTelemetry appears in the same category.

<img width="617" alt="opentelemetry" src="https://github.com/cncf/landscape2/assets/1213902/12271e3e-7f88-473c-b452-9fcccc90c618">

Regarding the description: it's possible to provide a description for an item by using the `description` field in the corresponding entry in the `landscape.yml` file. When it's not provided (like in this case), landscape2 uses the description of the main repository as a fallback (and landscape1 seems to be doing the same, as it shows the same description in the popup card). To list more repositories in addition to the Java SDK, you can use the `additional_repos` field (please see [this example from NATS as a reference](https://github.com/cncf/landscape/blob/0b71c07e0950fe915e192d370b7fb54c5560e618/landscape.yml#L5617-L5634)).

If you'd like to update this information, please submit a PR with the changes suggested to the [landscape.yml file in the cncf/landscape repository](https://github.com/cncf/landscape/blob/0b71c07e0950fe915e192d370b7fb54c5560e618/landscape.yml#L10067-L10094). That should fix this issue in both landscapes.

Hope this helps 🙂

**Comment by tegioz** [comment]
BTW thanks for the screenshot you shared. The groups selector wasn't being displayed correctly at the window size you used. The issue has been fixed and the fix will be deployed shortly 🙂
