### ISSUE TITLE
Provide ability to run a GTM container on the landscape site

### ISSUE THREAD

**Issue by cjyabraham** [cncf/landscape2#452]
Provide the ability to run a GTM container on landscape2. I would say this is an urgent need in order to keep CNCF analytics steady as we deploy landscape2. Currently, traffic to the CNCF landscape makes up for about half of all traffic to the CNCF websites.

**Comment by tegioz** [comment]
Thanks @cjyabraham, we'll take care of this very soon 👍

**Comment by tegioz** [comment]
Hi @cjyabraham

We've added initial support for this in #457. You can set it up for the CNCF landscape by creating a PR to add the GTM container id to the [CNCF settings file](https://github.com/cncf/landscape2-sites/blob/46a3212bf0312bd78b4d08802868bf8b345adf32/cncf/settings.yml#L30-L37) (please add the new section below the sample, to keep it as reference 😇).

Landscape2 uses a Content Security Policy that we've updated to allow GTM and GA4. To load additional tags we'll probably need to update the policy accordingly.
