### ISSUE TITLE
feature request: Customize footer in settings.yaml

### ISSUE THREAD

**Issue by gaocegege** [cncf/landscape2#476]
Thanks for the awesome tool. We wanna use it to create a landscape. But it seems that the footer is hard coded here: https://github.com/cncf/landscape2/blob/main/web/src/layout/navigation/Footer.tsx#L182

The copyright owner will always be LF. Could we allow users to specify the footer text?

**Comment by tegioz** [comment]
Thanks @gaocegege!

Sure, we can make that footer text configurable 👍

**Comment by gaocegege** [comment]
Thanks! It would be better if the github repository in the header https://github.com/cncf/landscape2/blob/main/web/src/layout/navigation/Header.tsx#L133 could support customization. Because the landscape website usually has a standalone repository.

Maybe we could add a footer e.g. `The landscape is powered by [landscape2](...)` to keep endorsement

**Comment by tegioz** [comment]
Done!

Closed by #483
