### ISSUE TITLE
Logo preview - hide Non-Public listings

### ISSUE THREAD

**Issue by taylorwaggoner** [cncf/landscape2#506]
Hi! In the [Logo Preview](https://cncf.landscape2.io/logos-preview), is it possible to filter out or hide the "Non-Public Organization" listings that appear as the animal silhouettes as their logo? The original purpose of these listings, from when the landscape was launched, is to be a placeholder for companies that opt out of adding their logo to the landscape, to keep the member count totals accurate.

Two things here - perhaps it's time to remove them completely from the landscape. @caniszczyk any concerns with that?

If we did keep them, another idea would be to rename them to something that makes them automatically appear at the end of the image in the Logo Preview, so that I can crop them out. 

Thanks!

**Comment by tegioz** [comment]
Closed by #594 🙂
