### ISSUE TITLE
Add Project View and Add Totals

### ISSUE THREAD

**Issue by taylorwaggoner** [cncf/landscape2#507]
Hi, 
It would be great if there was a specific CNCF project view, sorted by maturity level and not category. Currently I can filter for CNCF projects, but they are still sorted by category (https://landscape.cncf.io/?group=projects-and-products&view-mode=card&project=graduated&project=incubating&project=sandbox#app-definition-and-development--application-definition-image-build)

Also, would be great if there was a total # of projects in the header for each maturity level (ie "Graduated (23)), like it was in V1. This would also be helpful in the Member landscape for each membership tier. 

Thanks!

**Comment by tegioz** [comment]
This is ready @taylorwaggoner 🙂

Closed by #552

**Comment by taylorwaggoner** [comment]
Thank you!
