### ISSUE TITLE
GitHub Organisation Metrics

### ISSUE THREAD

**Issue by nikolaydubina** [cncf/landscape2#516]
I run https://neuroscience-landscape.com

We see often entities (Laboratories, Companies) do not have specific single repository.

Instead, they have GitHub Organization with lots of small repositories.

It would be good to show statistics for whole GitHub Organisation. Such as:
- number of repositories
- most common languages
- total stars

(I have hardfork coming up in coming week. I will share screenshots and you can try it out. If there is interest, and you like our approach, I can raise PR as well.).

**Comment by nikolaydubina** [comment]
I see that there is similar request: https://github.com/cncf/landscape2/issues/386

I think solution mentioned in that issue is good.

However, this is separate issue. Instated of statistics of each/many repositories, here we would like to get Organisation level overview.

**Comment by tegioz** [comment]
Hi @nikolaydubina 👋

Collecting metrics at the organization level would probably have a considerable impact both in the processing time and in the GitHub rate limit / tokens, as some organizations in the landscapes we maintain are quite large.

In some cases, only a repository may be relevant for a particular landscape item, so processing the entire organization would be a bit overkill. In other situations, there are multiple landscape items whose repositories are hosted in the same GitHub organization. This could be misleading for users as the same GitHub stats would be displayed for multiple landscape items (when they shouldn't).

We'll hold on a bit on this, but we'll ping you should the situation change. Thanks anyway! 🙂

BTW we've just added the repositories selector discussed on #386.
