### ISSUE TITLE
Add option to set default view via settings

### ISSUE THREAD

**Issue by cafkafk** [cncf/landscape2#530]
For https://landscape.nixlang.wiki we wanted to use the card view instead of the grid view as the default. Sadly, we currently have to compile our own version of landscap2 just to change this.

We would love if there was an option for this instead!

This part of the code might be relavant:
https://github.com/cncf/landscape2/blob/4365ca1a6eb3b175b57216d4ea9e602d4b286ef5/web/src/data.ts#L46

**Comment by tegioz** [comment]
Thanks @cafkafk, we'll make this configurable 🙂

**Comment by tegioz** [comment]
Done!

Closed by #572 and #574
