### ISSUE TITLE
Is there any setting that can support base url?

### ISSUE THREAD

**Issue by flyfishzy** [cncf/landscape2#542]
Hi, I am using cncf landscape2 to build a landscape web page for front-end opensource software. However, the current landscape2 does not support `base url`. Because I want to deploy it to a URL like `https://foo.github.io/landscape/`.
Is there any solution to this problem? 
FYI:  here is a vitepress base url config https://vitepress.dev/guide/asset-handling#base-url

> If your site is deployed to a non-root URL, you will need to set the base option in .vitepress/config.js. For example, if you plan to deploy your site to https://foo.github.io/bar/, then base should be set to '/bar/' (it should always start and end with a slash).

Many thanks!

**Comment by tegioz** [comment]
Hi @flyfishzy 👋

Not at the moment, but this is something we'd like to have to we'll take care of it 🙂

**Comment by flyfishzy** [comment]
Thanks a lot ! I'm really looking forward to it.

**Comment by tegioz** [comment]
This is ready @flyfishzy 🙂

You can see it in action in this repository: <https://github.com/tegioz/sample-landscape>

Closed by #557 and #561

**Comment by flyfishzy** [comment]
Thank you!!! It works for me.
