### ISSUE TITLE
Unable to hide "stats" primary navigation link

### ISSUE THREAD

**Issue by Relequestual** [cncf/landscape2#591]
Hello!

My team has created a landscape for our open source project's ecosystem. It's a great start!
We are not currently a foundation, and we do not have any projects in different stats.
So, as a result, the stats page is blank.

It would be great if the stats page could be disabled via settings config.

We very much appreciate all the work you are all doing here. Thanks!

**Comment by tegioz** [comment]
Hi @Relequestual 👋

We're glad you like it, thanks! It'd be great if you could add your landscape to the [adopters file](https://github.com/cncf/landscape2/blob/main/ADOPTERS.md) when you are ready 🙂

Regarding your request, maybe we could check when there are no stats at all to show and hide that navigation link automatically.

**Comment by Relequestual** [comment]
We will gladly add to the adopters file, thanks!

Yes, that sounds preferable. No need to configure then.

**Comment by tegioz** [comment]
> ~We will gladly add to the adopters file, thanks!~ Looks like we are on it! Woop!

@benjagm took care of it yesterday 😉

> Yes, that sounds preferable. No need to configure then.

Awesome 👍
