### ISSUE TITLE
The filter section appears empty 

### ISSUE THREAD

**Issue by DarhkVoyd** [cncf/landscape2#621]
Hello,

I am writing on behalf of the [JSON Schema](https://json-schema.org/) Project.
Currently, the filter box on our landscape appears empty but it would be great to enable it. We are unable to find any documentation regarding configuring filters. Our current understanding is that the tool expects to extract data from Crunchbase and GitHub API to populate the filter section. We tried using a Basic Crunchbase API but the build fails with `error decoding response body` for each entry in the landscape.yml file. Is there any additional configuration we are missing? How can we troubleshoot the "error decoding response body" error and configure filters.

Thank you!

**Comment by tegioz** [comment]
Hi @DarhkVoyd 👋

Filters are prepared dynamically based on the data available as you guessed, and some of them require information collected from GitHub or Crunchbase.

Filters are prepared per group as needed. Actually, one of your groups displays some filters, but others don't have enough data yet.

![some-filters](https://github.com/cncf/landscape2/assets/1213902/88b8fe4d-53d1-42f1-942a-1a82d84ad7e7)

![no-filters](https://github.com/cncf/landscape2/assets/1213902/8d2d29dd-ef0e-4f4d-b4a0-df0cc135e5f5)

These screenshots have been taken using a build from the main branch, which contains some improvements not available in any release yet. So it may vary a bit from what you see on your build. We'll cut a new release soon anyway 😉

About the Crunchbase data, please note that landscape2 needs access to the full Crunchbase API, which requires an enterprise or application license [1]. If you are using the basic Crunchbase API, it's likely that the response payload is different, hence the errors decoding it. You can confirm this by doing [the same request](https://github.com/cncf/landscape2/blob/78a0623ceaed1003c8bf0ae02273682cbc254142/crates/cli/src/build/crunchbase.rs#L237-L268) we do and checking if the output matches [what we expect](https://github.com/cncf/landscape2/blob/78a0623ceaed1003c8bf0ae02273682cbc254142/crates/cli/src/build/crunchbase.rs#L270-L274).

Hope this helps 🙂

[1] We'll add this information to the README file for future reference 😇
