### ISSUE TITLE
End User and Vendor Filtering

### ISSUE THREAD

**Issue by onlydole** [cncf/landscape2#639]
# Context

In recent communications, it was observed that the recent overhaul of the CNCF Landscape site has removed specific filters that help distinguish between end users and non-end users. This functionality is important for the KubeCon CFP pages, where co-chairs use this information to balance the distribution of end user and vendor speakers. The broken links have been causing 404 errors, and this issue needs attention.

# Impact

* Links on the KubeCon CFP pages leading to end user and non-end user distinctions are broken.
* Submitters need help determining their appropriate group easily, potentially leading to misclassification.
* The quality of our content and SEO is affected by these broken links.

# Proposal

* Reintroduce filters to distinguish between end and non-end users on the CNCF Landscape.

# Relevant Links:

* The old link for end users (now broken): https://landscape.cncf.io/card-mode?enduser=yes
* Example of the current KubeCon CFP page needing update: [KubeCon CFP End User Companies Section](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/program/cfp/#end-user-companies)

**Comment by MiirzaBaig** [comment]
Has anyone fix yet?
If not do please elaborate or specify the issue!

**Comment by tegioz** [comment]
Thanks @MiirzaBaig, we've already taken care of this 🙂 (I'd recommend you to take a look at <https://clotributor.dev>, where you can find lots of issues looking for help).

<hr/>

We've just added a new `end user` filter @onlydole. It's available from the UI (see screenshot below), so you can easily combine it with other filters to produce the link you need.

The equivalent of

<https://landscape.netlify.app/card-mode?enduser=yes>

in landscape v2 would be

<https://landscape.cncf.io/?group=members&view-mode=card&classify=category&enduser=true>

But maybe you want to apply some extra filtering, select a different order or grouping for the cards, etc. So feel free to tweak it as needed 😉

<img width="1683" alt="end_user_filter" src="https://github.com/cncf/landscape2/assets/1213902/c1c78a74-e432-48bf-92a4-179764796204"><br/>

Closed by #647, #646 and cncf/landscape2-sites#90.

**Comment by onlydole** [comment]
Thank you so much, @tegioz!
