### ISSUE TITLE
Embed view - have popup show on current page rather than open a new one ( landscape v1 behavior )

### ISSUE THREAD

**Issue by jmertic** [cncf/landscape2#643]
Hi! This has come up a few times with the embed, latest is below...

> Since we embedded the General Members from the landscape to the website, the section is currently clickable and drives people to the actual landscape. Could you help us adjust the setting so it will be more like the https://www.aswf.io/members/ page, essentially not directing people to the actual landscape?

Any chance the behavior from v1 could be restored as an option?

**Comment by jmertic** [comment]
Bump @tegioz :-)

**Comment by tegioz** [comment]
Hi @jmertic @Noraanwar 👋

We are working on this and we expect to have a first version ready soon 🙂

**Comment by tegioz** [comment]
This is ready 🙂

<img width="812" alt="item-details-modal" src="https://github.com/user-attachments/assets/a3aaac03-8fc1-4303-9253-506cf406d130">

Closed by #664

**Comment by tegioz** [comment]
Hi @Noraanwar

This feature requires adding an extra iframe and script to the embedding page. You can get the new code from the `/embed-setup` page in your landscape after selecting the option I shared in my previous comment. The [demo](https://codepen.io/cynthiasg/pen/WNmQjje) referenced in the repository's README file has also been updated to use this feature, just in case it helps.

<img width="1373" alt="embed-code" src="https://github.com/user-attachments/assets/4ba8c800-ec58-400e-85f3-46fa10d0936b">
