### ISSUE TITLE
Add a "sheet view" that shows metadata from the landscape for projects

### ISSUE THREAD

**Issue by caniszczyk** [cncf/landscape2#659]
We are trying to replicate a similar view to https://docs.google.com/spreadsheets/d/12CR7zP5c6r98k5TQ--xIR7j386sO_pL6kjmFOPZkepw/edit?gid=0#gid=0

<img width="546" alt="Screenshot 2024-07-08 at 10 13 42 AM" src="https://github.com/cncf/landscape2/assets/63777/1c30f84b-5d82-4ad4-a0c4-da89f136278c">

Essentially listing Project, Year Accepted, Date, Date Moved to Incubation, Date Moved to Graduated

**Comment by jeefy** [comment]
Other parts of the sheet include CLOMonitor-style data. IMO we don't need to pull any of that in for an MVP.

A top-level column showing the "state" (sandbox/incubating/graduated/archived) would be good, even if it's an aggregate field since dates are there.

**Comment by caniszczyk** [comment]
@jeefy I'd skip all the clomonitor data for now, just keep it simple

Another idea is that it may just be easier to have a CSV dump / sheet view in CLOMonitor for this https://github.com/cncf/clomonitor/issues/1527

**Comment by tegioz** [comment]
Please see: https://github.com/cncf/clomonitor/issues/1527#issuecomment-2216718071 🙂

**Comment by tegioz** [comment]
<https://landscape.cncf.io/projects>

<img width="1676" alt="projects" src="https://github.com/user-attachments/assets/4000b3c3-ad03-48fb-958f-74b717199a61">

Closed by #666
