### ISSUE TITLE
Sample data.yml has invalid type at `extra` field 

### ISSUE THREAD

**Issue by trongthanh** [cncf/landscape2#701]
I'm setting up a new landscape project using landscape2 0.10.0 and sample [data.yml](https://github.com/cncf/landscape2/blob/main/docs/config/data.yml) from this repo and getting this error:

```
[build] Error: invalid yaml file

Caused by:
    categories[0].subcategories[0].items[2].extra: invalid type: sequence, expected struct ItemExtra at line 32 column [build] 15
```

Looking closer at the error, I believe the error is caused by the data.yml has [unwanted dash `-` after the `extra` field](https://github.com/cncf/landscape2/blob/main/docs/config/data.yml#L99), making it a sequence type instead of a struct.

**Comment by tegioz** [comment]
Hi @trongthanh 👋

You're right, that's a typo in the sample data file.

Thanks for bringing this up, we'll take care of it 👍
