### ISSUE TITLE
Bug: End User display incomplete on landscape.cncf.io

### ISSUE THREAD

**Issue by onlydole** [cncf/landscape2#710]
## Description
The End User display on https://landscape.cncf.io/?group=members&enduser=true is not showing all End Users across their membership and supporter levels. We expect to see approximately 160 End Users, but the current display shows fewer than this.

## Expected Behavior
All End Users (approximately 160) should be visible when filtering for End Users across all membership and supporter levels.

## Steps to Reproduce
1. Navigate to https://landscape.cncf.io/
2. Apply the following filters:
   - Filter By: Extra > End user
3. Observe the number of End Users displayed

**Comment by tegioz** [comment]
Hi @onlydole 👋

At the moment there are 63 entries in the `landscape.yml` file with the field `enduser` field set to true, which matches what we show in the landscape.

However, until a month ago, we were considering the items in the `end user supporter` subcategory as end users as well. This would explain the number of missing items.

We talked to @taylorwaggoner about this, as we were marking items both as `end user supporter` and `end user`, and we agreed that both weren't needed and `end user supporter` was a better fit. But I forgot to mention that this would imply that entries in that subcategory wouldn't show up when filtering by `end user`.

In any case, this is easy to fix, as it's just a configuration change. Just to confirm, would you like to mark all items in the `end user supporter` subcategory as `end users`? If so, we just need to revert [this change](https://github.com/cncf/landscape2-sites/commit/ebb776bf0afc012adc51aa015f1d05d124f56792) 🙂

**Comment by onlydole** [comment]
Thank you, @tegioz - That membership tier is not considered a full member, though I would like them to be added to the filter under "End User" for that filter. I've added a PR (let me know if I need to change anything on that end).

> https://github.com/cncf/landscape2-sites/pull/101

**Comment by tegioz** [comment]
Thanks @onlydole, the PR has been merged and the changes should be visible as soon as the landscape is built again (in a few hours ;)

**Comment by onlydole** [comment]
Thank you so much, @tegioz
