### ISSUE TITLE
Include iframe resizer code in embed code

### ISSUE THREAD

**Issue by jmertic** [cncf/landscape2#734]
For the code snippet provided for embedding a landscape view, have an option to include the iframe resizer code. This makes it a bit easier to copy and paste a code snippet to provide to web designers. Thanks!

**Comment by tegioz** [comment]
Makes sense @jmertic, we'll take care of it soon 👍

**Comment by jmertic** [comment]
Much appreciated - thank you @tegioz

**Comment by tegioz** [comment]
Hi @jmertic 

As discussed on Slack, `iframe-resizer` changed its license in v5 ([1](https://github.com/davidjbradshaw/iframe-resizer/releases/tag/5.0.0), [2](https://iframe-resizer.com/licenses/), [3](https://iframe-resizer.com/pricing/)). We'll leave current support for v4 (MIT license) as it is, but we'd rather not to encourage its usage anymore as we won't be able to support it going forward.

Thanks anyway!
