### ISSUE TITLE
Would like to add another icon on the footer that is not one of the precreated types

### ISSUE THREAD

**Issue by narausch** [cncf/landscape2#738]
In the settings in the footer I would like to be able to create another icon for a general server we use for discussions:  

footer:
  links:
     <other links>
      discussions: "https://discuss.pytorch.org/"

There doesnt seem to be a way to be able to do this.  I added it but it does not show up.  Is there a way to add an icon and a link for the footer, or could one be created?

**Comment by tegioz** [comment]
Closed by #760
