### ISSUE TITLE
Create pytorch as a new site in https://github.com/cncf/landscape2-sites/pytorch

### ISSUE THREAD

**Issue by narausch** [cncf/landscape2#739]
I have put together all the pytorch code for a landscape2.  Here is that code: https://github.com/pytorch/landscape.  I cannot seem to create a branch however in the https://github.com/cncf/landscape2-sites/ to add my repo.  

Can you please either grant me access to be able to branch and create a pull request in this repo, https://github.com/cncf/landscape2-sites/pytorch, or do it for me?  

i have the logos, settings, landscape, and group yaml files.

**Comment by tegioz** [comment]
Thanks, done! https://github.com/cncf/landscape2-sites/pull/115
