### ISSUE TITLE
Embed Preview not rendering with base_path set

### ISSUE THREAD

**Issue by randyoun** [cncf/landscape2#741]
In 0.11.0 the preview in the Embed setup fails to render and shows an "Invalid embed url" error when setting a base_path in settings.yml.  When I remove the base_path things seems to work.

Confirmed same behavior on a couple different browsers.  I'm happy to gather/share more details as needed especially if unable to reproduce.

**Comment by cynthia-sg** [comment]
Hi @randyoun  👋

Thanks for reporting this! We've been able to reproduce it and it has been fixed [here](https://github.com/cncf/landscape2/pull/742).

🙂
