### ISSUE TITLE
Add additional common social

### ISSUE THREAD

**Issue by jmertic** [cncf/landscape2#750]
We have covered these fields in the metadata...

```
LinkedIn
Twitter
YouTube:
```

Could we also add these? Yes, I know there is a desire to put them under `other_links`, but they do seem to be similarly first-class like the above.

```
Facebook
Pinterest
Reddit
```

**Comment by k-vijay-05** [comment]
@jmertic can i work on this?

**Comment by tegioz** [comment]
There is already someone working on this issue @k-vijay-05, but thanks anyway 🙂

**Comment by tegioz** [comment]
Closed by #759
